// Root layout, all pages share this structure
// Vercel Analytics included (no Google Analytics, blocked by Great Firewall, V7 §6.1 Option C)
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ScrollToTop from '@/components/ScrollToTop';
import '@/styles/globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://synergisticinteraction.com.au';

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: 'Synergistic Interaction: Practical AI Adoption for Australian Business',
    template: '%s, Synergistic Interaction',
  },
  description:
    'Practical AI adoption for established Australian businesses and practices. A fixed-price readiness assessment, the right tools and workflows, staff training, and a human always in the loop.',
  keywords: [
    'AI adoption',
    'AI consulting Australia',
    'AI for small business',
    'AI change management',
    'AI readiness assessment',
    'bespoke AI',
    'AI implementation',
    'responsible AI',
  ],
  authors: [{ name: 'Joshua Thompson', url: BASE_URL }],
  creator: 'Synergistic Interaction',
  publisher: 'Synergistic Interaction',
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  alternates: {
    canonical: BASE_URL,
    languages: {
      'en-AU': BASE_URL,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_AU',
    url: BASE_URL,
    siteName: 'Synergistic Interaction',
    title: 'Synergistic Interaction: Practical AI Adoption for Australian Business',
    description:
      'Practical AI adoption for established Australian businesses and practices. The right tools, staff trained, and a human always in the loop.',
    // og:image is generated by app/opengraph-image.tsx via the file convention.
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Synergistic Interaction: Practical AI Adoption for Australian Business',
    description: 'Practical AI adoption for established Australian businesses and practices.',
  },
  icons: {
    icon: '/logo-icon.svg',
    apple: '/logo-icon.svg',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en-AU" className={inter.variable}>
      <head>
        <link rel="alternate" hrefLang="en-AU" href={BASE_URL} />
        <link rel="alternate" hrefLang="x-default" href={BASE_URL} />
        {/* V7 §6.1 Option C: NO Google Fonts here, CJK fonts use system stack only */}
        {/* V7 §6.1 Option C: NO Google Analytics, use Vercel Analytics (not blocked) */}
      </head>
      <body className="bg-si-bg text-si-white min-h-screen flex flex-col antialiased">
        <Header />
        <div className="flex-1">{children}</div>
        <Footer />
        {/* Vercel Analytics, not blocked by Great Firewall */}
        <Analytics />
        <ScrollToTop />
      </body>
    </html>
  );
}
